# 是否開啓功能
broadcast: true
score_image: true

# 其他設定
font: "./assets/TaipeiSansTCBeta-Bold.ttf"

# broadcast
channels_regexp: 隊伍\d+

# score_image
image_for_score: "./assets/apex_background.png"
image_with_color_block: "./assets/apex_with_color_block.png"

# 還有「額外分」這關鍵字可以使用，格式是「隊伍index: points」
# 但因爲懶惰原因，會加到排名分裏面，造成驗證訊息不可信
round_name_map: ["一", "二", "三", "四", "五", "六"]
ranking_score_map: {
    1: 12,
    2: 9,
    3: 8,
    4: 6,
    5: 6,
    6: 4,
    7: 4,
    8: 4,
    9: 4,
    10: 4,
    11: 2,
    12: 2,
    13: 2,
    14: 2,
    15: 2,
}
kill_ranking_bonus_score_map: {1: 0, 2: 0, 3: 0}

# 請選擇輸出的數據（0～5）
# [簡稱, 隊名, 總擊殺, 總排名分, Bonus, 總分數]
output_data: [1, 5]

# 請選擇圖片上，要與數據對應的顏色（與數據的數量一致，並且順序一致）
output_color:
- [189, 97, 255]
- [231, 158, 0]

# 按照哪些數據排序？（可多選，依序排序）
# ！！！注意！！！這裏的index是按照output_data的數量，
# 重新獲取的list決定，假設上面是[1, 5]，那就只剩下兩個index
# 也就是[0, 1]
order_by: [1]
